import os

content = (
    'import {\n'
    '  Box, Button, Collapse, Divider, List,\n'
    '  ListItem, ListItemButton, ListItemIcon, ListItemText, Typography\n'
    '} from \'@mui/material\';\n'
    'import { Check, ExpandLess, ExpandMore } from \'@mui/icons-material\';\n'
    'import { FILTER_SECTIONS } from \'../constants\';\n'
    'import RangeSliderFilter from \'./RangeSliderFilter\';\n'
    '\n'
    'const FilterDrawerContent = ({\n'
    '  filters, openSections, sectionOptions,\n'
    '  dataRanges, wordCountRange, sentenceCountRange,\n'
    '  hasUnappliedChanges, hasActiveFilters,\n'
    '  toggleFilter, toggleSection,\n'
    '  setWordCountRange, setSentenceCountRange,\n'
    '  applyFilters, clearAll\n'
    '}) => {\n'
    '  const rangeSliders = dataRanges ? [\n'
    '    {\n'
    '      key: \'wordCount\',\n'
    '      label: \'S\u00f5nade arv\',\n'
    '      range: dataRanges.wordCount,\n'
    '      value: wordCountRange ?? dataRanges.wordCount,\n'
    '      onChange: setWordCountRange,\n'
    '      onReset: () => setWordCountRange(null),\n'
    '      isActive: !!(wordCountRange && (wordCountRange[0] > dataRanges.wordCount[0] || wordCountRange[1] < dataRanges.wordCount[1]))\n'
    '    },\n'
    '    {\n'
    '      key: \'sentenceCount\',\n'
    '      label: \'Lausete arv\',\n'
    '      range: dataRanges.sentenceCount,\n'
    '      value: sentenceCountRange ?? dataRanges.sentenceCount,\n'
    '      onChange: setSentenceCountRange,\n'
    '      onReset: () => setSentenceCountRange(null),\n'
    '      isActive: !!(sentenceCountRange && (sentenceCountRange[0] > dataRanges.sentenceCount[0] || sentenceCountRange[1] < dataRanges.sentenceCount[1]))\n'
    '    }\n'
    '  ] : [];\n'
    '\n'
    '  return (\n'
    '    <div>\n'
    '      <Box className="sv2-drawer-header">\n'
    '        <Typography variant="overline" display="block" sx={{ color: \'#4a148c\', lineHeight: 1.5 }}>\n'
    '          Filtrid\n'
    '        </Typography>\n'
    '      </Box>\n'
    '      <Divider />\n'
    '\n'
    '      <List dense disablePadding>\n'
    '        {FILTER_SECTIONS.map(({ key, label }) => {\n'
    '          const selected = filters[key];\n'
    '          const count = selected?.size || 0;\n'
    '          const isOpen = openSections.has(key);\n'
    '          const options = sectionOptions[key] || [];\n'
    '\n'
    '          return (\n'
    '            <div key={key}>\n'
    '              <ListItem disablePadding>\n'
    '                <ListItemButton onClick={() => toggleSection(key)}>\n'
    '                  <ListItemText\n'
    '                    primary={\n'
    '                      <Box sx={{ display: \'flex\', alignItems: \'center\', gap: 0.75 }}>\n'
    '                        <span>{label}</span>\n'
    '                        {count > 0 && <span className="sv2-filter-badge">{count}</span>}\n'
    '                      </Box>\n'
    '                    }\n'
    '                  />\n'
    '                  {isOpen ? <ExpandLess fontSize="small" /> : <ExpandMore fontSize="small" />}\n'
    '                </ListItemButton>\n'
    '              </ListItem>\n'
    '              <Collapse in={isOpen} timeout="auto" unmountOnExit>\n'
    '                <List dense disablePadding>\n'
    '                  {options.map(id => {\n'
    '                    const isSelected = selected?.has(id);\n'
    '                    return (\n'
    '                      <ListItemButton\n'
    '                        key={id} selected={isSelected}\n'
    '                        onClick={() => toggleFilter(key, id)}\n'
    '                        sx={{ pl: 1.5 }}\n'
    '                      >\n'
    '                        <ListItemIcon sx={{ minWidth: 32 }}>\n'
    '                          <Check\n'
    '                            fontSize="small"\n'
    '                            sx={{ color: \'#9c27b0\', opacity: isSelected ? 1 : 0, fontSize: 16, transition: \'opacity 0.15s\' }}\n'
    '                          />\n'
    '                        </ListItemIcon>\n'
    '                        <ListItemText primary={id} />\n'
    '                      </ListItemButton>\n'
    '                    );\n'
    '                  })}\n'
    '                </List>\n'
    '              </Collapse>\n'
    '              <Divider />\n'
    '            </div>\n'
    '          );\n'
    '        })}\n'
    '      </List>\n'
    '\n'
    '      {rangeSliders.map(({ key, ...props }) => (\n'
    '        <RangeSliderFilter\n'
    '          key={key}\n'
    '          {...props}\n'
    '          isOpen={openSections.has(key)}\n'
    '          onToggle={() => toggleSection(key)}\n'
    '        />\n'
    '      ))}\n'
    '\n'
    '      <Box className="sv2-drawer-footer" sx={{ display: \'flex\', flexDirection: \'column\', gap: 0.5 }}>\n'
    '        <Button\n'
    '          variant="contained" size="small" fullWidth\n'
    '          onClick={applyFilters}\n'
    '          sx={{\n'
    '            textTransform: \'none\', fontWeight: 600, bgcolor: \'#9c27b0\',\n'
    '            \'&:hover\': { bgcolor: \'#6a1b9a\' },\n'
    '            outline: hasUnappliedChanges ? \'2px solid #ce93d8\' : \'none\',\n'
    '            outlineOffset: \'2px\'\n'
    '          }}\n'
    '        >\n'
    '          {hasUnappliedChanges ? \'Rakenda filtrid \u25cf\' : \'Rakenda filtrid\'}\n'
    '        </Button>\n'
    '        <Button\n'
    '          variant="text" size="small"\n'
    '          disabled={!hasActiveFilters && !hasUnappliedChanges}\n'
    '          onClick={clearAll}\n'
    '          sx={{ fontSize: \'0.75rem\', textTransform: \'none\', color: \'#9c27b0\' }}\n'
    '        >\n'
    '          Kustuta k\u00f5ik filtrid\n'
    '        </Button>\n'
    '      </Box>\n'
    '    </div>\n'
    '  );\n'
    '};\n'
    '\n'
    'export default FilterDrawerContent;\n'
)

path = r'D:\Projektid\ELLE\evkk\ui\src\elle\pages\statisticsV2\components\FilterDrawerContent.jsx'
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Written', len(content), 'chars')

